### ISSUE TITLE
adding a weak model to aider cmd?

### ISSUE THREAD

**Issue by masaruduy** [dubaigit/aider_split_install#1]
what do you think of adding in something like "--weak-model openrouter/deepseek/deepseek-coder" the aider cmd?

**Comment by dubaigit** [comment]
Yes you can, test it out and tell me

**Comment by masaruduy** [comment]
Actually, using the whole prompt seems to break the "don't remove code when
it says "remains the same"

**Comment by dubaigit** [comment]
it should not write code only instructions for aider to write the code
cline will manage aider remind him in chat to write in the instruction file
and use aider

and update me
